
title: Introduction to Design Thinking 
description: Design Thinking is a human-centric approach to creating solutions.  This course will teach you the principles of Design Thinking and walk you through applying its five phases to your projects. 
template:
  name: design-thinking-intro
  repo: design-thinking-intro-template
before:
- type: createIssue
  title: Welcome
  body: 00_welcome.md
- type: updateBranchProtection

# Course artifacts:
# 1. Issue: Welcome
# 2. PR: Intro to Design Thinking
# 3. PR: Five Phases
# 4. PR: Empathy
# 5. PR: Define & Ideate
# 6. PR: Prototype & Test
# 5: Issue: Publish your toolkit


# Template repo
# branch main:
# _config.yml

# branch minimum-viable-product: 
# - mvp/README.md

# branch intro:
# - five-phases/README.md

# branch phase-one:
# - empathy/README.md

# branch phases-two-and-three:
# - define-and-ideate/README.md

# branch phases-four-and-five:
# - prototype-and-test/README.md


# Final filetree:
# _config.yml: configure the GitHub Pages site
# README.md
# + mvp
# +- README.md
# + five-phases
# +- README.md
# + empathy
# +- README.md
# + define-and-ideate
# +- README.md
# + prototype-and-test
# +- README.md


steps:

#1
- title: Answer your first challenge question
  description: Determine the focus of Design Thinking.
  # what we expect the learner to do
  link: '{{ repoUrl }}/issues/1'
  event: issues.edited #answer the question
  # prepping the learner for the NEXT step
  actions:
  - type: createPullRequest
    title: Intro to Design Thinking
    head: minimum-viable-product #branch merging from
    body: 01_intro-design-thinking.md
    action_id: introPR
  # how we validate that the learner did it right
  - type: respond
    with: 01_technology-answer.md
    data: 
      url: '%actions.introPR.data.html_url%'
  - type: closeIssue

#2
- title: Answer the MVP challenge
  description: Discover the definition of MVP and important considerations in Design Thinking.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.edited
  actions:
 # - type: removeBranchProtection
 #   required: false
  - type: respond
    with: 02_intro-answer.md # this has the first PR in it

#3
- title: Merge the MVP pull request
  description: Beef up your Design Thinking toolkit with resources about Minimum Viable Product.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.closed
  actions:
#  - type: updateBranchProtection
#    required: false
  - type: createPullRequest
    title: Principles and Phases of Design Thinking
    head: intro
    body: 03_three-principles.md
    action_id: phasesPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.phasesPR.data.html_url%'  

#4
- title: Answer the core principles challenge
  description: Learn about the three central principles of Design Thinking.
  link: '{{ repoUrl }}/pull/3'
  event: issue_comment.created
  actions:
#  - type: removeBranchProtection
#    required: false
  - type: respond
    with: 04_three-principles-answer.md

#5
- title: Merge the five phases pull request
  description: Add resources about the five phases of Design Thinking to your toolkit.
  link: '{{ repoUrl }}/pull/3'
  event: pull_request.closed
  actions:
#  - type: updateBranchProtection
 #   required: false
  - type: createPullRequest
    title: Phase One - Empathize
    head: phase-one
    body: 05_empathize.md
    action_id: empathyPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.empathyPR.data.html_url%'

#6
- title: Answer the empathize challenge question
  description: Learn how to use empathy as a tool in Design Thinking.
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.edited
  actions:
 # - type: removeBranchProtection
 #   required: false
  - type: respond
    with: 06_empathize-answer.md

#7
- title: Merge the empathize pull request
  description: Add the empathy content to your Design Thinking toolkit.
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.closed
  actions:
#  - type: updateBranchProtection
#    required: false
  - type: createPullRequest
    title: Phases Two & Three - Define & Ideate
    head: phase-two-and-three
    body: 07_define.md
    action_id: definePR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.definePR.data.html_url%'


#add the define & ideate content
#8
- title: Answer the define & ideate challenge question
  description: Learn how to use the define & ideate phases of Design Thinking.
  link: '{{ repoUrl }}/pull/5'
  event: pull_request.edited
  actions:
 # - type: removeBranchProtection
 #   required: false
  - type: respond
    with: 07_define-answer.md

#9
- title: Merge the define & ideate pull request
  description: Add the define & ideate content to your Design Thinking toolkit.
  link: '{{ repoUrl }}/pull/5'
  event: pull_request.closed
  actions:
#  - type: updateBranchProtection
#   required: false
  - type: createPullRequest
    title: Phases Four & Five - Prototype & Test
    head: phase-four-and-five
    body: 08_prototype.md
    action_id: prototypePR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.prototypePR.data.html_url%'

#add the prototype & test content
#10
- title: Answer the prototype & test challenge question
  description: Learn how to use the prototype & test phases of Design Thinking.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request.edited
  actions:
 # - type: removeBranchProtection
 #   required: false
  - type: respond
    with: 08_prototype-answer.md

#11
- title: Merge the prototype & test pull request
  description: Add the prototype & test content to your Design Thinking toolkit.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request.closed
  actions:
#  - type: updateBranchProtection
#    required: false
  - type: createIssue
    title: Publish your toolkit
    body: 09_publish.md
    action_id: publishIssue
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.publishIssue.data.html_url%'



#12
- title: Enable GitHub Pages
  description: Publish your Design Thinking toolkit by turning on GitHub Pages. 
  link: '{{ repoUrl }}/pull/7'
  event: page_build
  actions:
 # - type: removeBranchProtection
 #    required: false
  - type: octokit
    method: repos.getPages
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    action_id: pagesUrl
  - type: respond
    issue: Publish your toolkit
    with: 10_congratulations.md
    data:
      deploymentURL: '%actions.pagesUrl.data.html_url%'
      forkURL: '%payload.repository.html_url%/fork'
      downloadURL: '%payload.repository.html_url%/archive/main.zip'


